logging_path: logs/ddqn_runner
pipeline_id:

seed: 2

train_file: "data/train/spy_train_ti.csv"
eval_file: "data/eval/spy_eval_2023_ti.csv"

start_cash_balance: 100000
cash_at_risk: 0.85

lookback: 60

take_profit_threshold: 0.01
stop_loss_threshold: 0.01
max_stop_loss_calls: 3

# gamma controls how much previous rounds influence reward
gamma: 0.999
epsilon: 1.0
batch_size: 128
eps_min: 0.1
eps_dec: 0.0005
n_features: 18
lr: 0.00001
hid_out_dims: [32,64,32]
dropout_size_list: [0.25,0.5,0.25]
replace_cnt: 100

# if loading a checkpoint, the previous run's pipeline_id must be provided
load_checkpoint: False

n_games: 2

save_model: True