logging_path: logs/ddqn_runner
pipeline_id:

seed: 2

train_file: "data/train/spy_train.csv"
eval_file: "data/eval/spy_eval.csv"

start_balance: 100000
cash_at_risk: 0.75

lookback: 45

# gamma controls how much previous rounds influence reward
gamma: 0.99
epsilon: 1.0
batch_size: 64
eps_min: 0.01
eps_dec: 0.0005
n_features: 6
lr: 0.001
replace_cnt: 100

# if loading a checkpoint, the previous run's pipeline_id must be provided
load_checkpoint: False

n_games: 250

save_model: True