logging_path: logs/philbot_runner
pipeline_id:

seed: 2

trade_file: "data/test/spy_test.csv"

cash_at_risk: 0.75

# gamma controls how much previous rounds influence reward
gamma: 0.99
epsilon: 1.0
batch_size: 64
eps_min: 0.01
eps_dec: 0.0005
input_dims: [6]
lr: 0.001
replace_cnt: 100

load_checkpoint: False

n_games: 1000