logging_path: logs/ddqn_runner
pipeline_id:

seed: 2

train_file: "data/train/spy_train_ti.csv"
eval_file: "data/eval/spy_eval_ti.csv"

start_balance: 100000
cash_at_risk: 0.75

lookback: 30

# gamma controls how much previous rounds influence reward
gamma: 0.99
epsilon: 1.0
batch_size: 32
eps_min: 0.01
eps_dec: 0.0005
n_features: 16
lr: 0.00001
hid_out_dims: 512
dropout: 0.5
replace_cnt: 100

# if loading a checkpoint, the previous run's pipeline_id must be provided
load_checkpoint: False

n_games: 250

save_model: True