logging_path: logs/philbot_runner
pipeline_id:

trade_file: "data/test/spy_test.csv"

cash_at_risk: 0.1

gamma: 0.99
epsilon: 1.0
batch_size: 64
eps_min: 0.01
eps_dec: 0.0005
input_dims: [6]
lr: 0.003

n_games: 200