logging_path: "/tmp/logs"
pipeline_id:

api_key: *****
api_secret: *****
base_url: "https://paper-api.alpaca.markets/v2"

start_date: "2019-12-15"
end_date: "2024-12-31"

timeframe_str: Day

symbol: SPY